export const jobData = [
  {
    id: 1,
    url: "recruitment",
    link: "bit.ly/EnglishSpaceApplicationForm",
    titleJob: "Recruitment",
    department: "Human Resources",
    skills: ["Screening", "Negoisasi", "recruitment process"],
    qualifications: [
      "Mahasiswa/i semester 2-4",
      "Memiliki ketertarikan tinggi dalam bidang edukasi bahasa Inggris dan startup",
      "Preferably domisili di sekitar Jakarta dan Tangerang Selatan",
      "Memiliki pengetahuan dasar mengenai proses recruitment and selection",
      "Mampu melakukan talent sourcing",
      "Dapat melakukan interview dan merekam jawaban interview dengan benar",
    ],
    description: [
      "Mencari talent dan melakukan screening",
      "Mempersiapkan dan melakukan wawancara",
      "Memberikan dan menegosiasikan tawaran kerja",
      "Menjaga hubungan di masa offer dan onboarding",
    ],
  },
  {
    id: 2,
    url: "training-and-development",
    link: "bit.ly/EnglishSpaceApplicationForm",
    titleJob: "Training and Development",
    department: "Human Resources",
    skills: ["Management", "Analysis", "Problem Solving"],
    qualifications: [
      "Mahasiswa/i semester 2-4",
      "Memiliki ketertarikan tinggi dalam bidang edukasi bahasa Inggris dan startup",
      "Preferably domisili di sekitar Jakarta dan Tangerang Selatan",
      "Memiliki kemampuan analisa dan riset untuk menyelesaikan suatu masalah",
      "Memiliki kemampuan untuk mengukur dan menilai kebutuhan pelatihan",
      "Memiliki kemampuan manajerial yang tinggi",
    ],
    description: [
      "Membuat training need analysis ",
      "Membuat perencanaan pelatihan",
      "Melakukan performance appraisal ",
      "Memastikan kinerja setiap individu berjalan dengan baik",
    ],
  },
  {
    id: 3,
    url: "payroll",
    link: "bit.ly/EnglishSpaceApplicationForm",
    titleJob: "Payroll",
    department: "Human Resources",
    skills: ["Screening", "Negoisasi", "recruitment process"],
    qualifications: [
      "Mahasiswa/i semester 2-4",
      "Memiliki ketertarikan tinggi dalam bidang edukasi bahasa Inggris dan startup",
      "Preferably domisili di sekitar Jakarta dan Tangerang Selatan",
      "Memiliki pemahaman atas regulasi penggajian dan insentif karyawan",
      "Memiliki tingkat perhatian pada detail dan akurasi yang tinggi",
      "Memiliki kemampuan berhitung yang baik ",
    ],
    description: [
      "Membuat dan tracking absensi karyawan",
      "Melakukan pendataan karyawan baru dan keluar",
      "Membuat laporan gaji bulanan karyawan",
      "Menghitung dan membayar gaji karyawan",
    ],
  },
  {
    id: 4,
    url: "uiux",
    link: "bit.ly/EnglishSpaceApplicationForm",
    titleJob: "UI/UX",
    department: "Technology",
    skills: ["Design", "Figma", "Adobe", "Detail", "Wireframe"],
    qualifications: [
      "Mahasiswa/i semester 2-4",
      "Memiliki ketertarikan tinggi dalam bidang edukasi bahasa Inggris dan startup",
      "Preferably domisili di sekitar Jakarta dan Tangerang Selatan",
      "Menguasai software design seperti Figma atau Adobe Photoshop atau Adobe Illustrator.",
      "Pemahaman yang kuat tentang wireframe tools",
      "Dapat melakukan praktik terbaik terkait UI/UX design serta memiliki pemahaman mendalam tentang mobile-first dan responsive design",
      "Berpengalaman untuk membuat wireframes, prototypes, storyboards, dan user flows",
      "Mempunyai pengetahuan terkait Design System",
      "Memiliki manajemen waktu yang baik serta dapat memenuhi deadline",
      "Memperhatikan detail",
    ],
    description: [
      "Melakukan pengumpulan dan evaluasi kebutuhan pengguna lewat kolaborasi dengan product engineer",
      "Membuat ilustrasi ide desain produk lewat alur proses maupun storyboard",
      "Merancang elemen antarmuka pengguna seperti grafis menu, tab, dan widget",
      "Mengembangkan mockup dan prototipe tampilan antarmuka untuk menggambarkan fungsi dan kinerja produk",
      "Membuat grafis atau draf kasar untuk pemaparan kepada timal dan para stakeholders",
      "Penyesuaian tata letak berdasarkan umpan balik pengguna",
    ],
  },
  {
    id: 5,
    url: "frontend-developer",
    link: "bit.ly/EnglishSpaceApplicationForm",
    titleJob: "Frontend Developer",
    department: "Technology",
    skills: ["ReactJS", "Javascript", "Webpack", "Redux", "API"],
    qualifications: [
      "Mahasiswa/i semester 2-4",
      "Memiliki ketertarikan tinggi dalam bidang edukasi bahasa Inggris dan startup",
      "Preferably domisili di sekitar Jakarta dan Tangerang Selatan",
      "Menguasai dan mahir menggunakan HTML, CSS, JavaScript",
      "Memiliki pengalaman menggunakan JavaScript Framework seperti React JS dan Vue JS",
      "Menguasai front end developer tools seperti NPM / Yarn, Webpack, atau yang lain",
      "Memahami prinsip-prinsip desain situs web dan optimasi SEO",
      "Mampu menggunakan code versioning tools seperti Git",
      "Memiliki pengalaman dengan Front End Frameworks dan RESTful Services/APIs, Git/Version Control",
      "Dapat menggunakan CSS framework seperti Bootstrap, Material Ui, atau Tailwind",
      "Keterampilan troubleshoot yang baik",
    ],
    description: [
      "Merancang ide dasar tampilan website/aplikasi bersama dengan desainer UX",
      "Memastikan tampilan program yang dirancang sesuai dengan teknis desain dari UI/UX",
      "Mengelola kecepatan dari website/aplikasi sehingga bisa berjalan dengan optimal",
      "Menerapkan elemen visual situs atau aplikasi yang telah dirancang oleh desainer UI sebelumnya",
      "Menggunakan desain responsif dalam pembuatan interface pengguna situs web atau aplikasi",
      "Menguji situs atau aplikasi secara fungsional bersama dengan tim developer lainnya",
      "Memecahkan yang terjadi pada saat uji coba peluncuran program",
      "Memastikan bahwa uji kelayakan dari segi tampilan selesai sebelum mengirimkannya ke tim back end",
      "Meningkatkan arsitektur visual situs atau aplikasi bersama dengan back end developer",
    ],
  },
  {
    id: 6,
    url: "accounting",
    link: "bit.ly/EnglishSpaceApplicationForm",
    titleJob: "Accounting",
    department: "Finance",
    skills: ["Excel", "Laporan Keuangan", "Pencatatan", "Detail"],
    qualifications: [
      "Mahasiswa/i semester 2-4",
      "Memiliki ketertarikan tinggi dalam bidang edukasi bahasa Inggris dan startup",
      "Preferably domisili di sekitar Jakarta dan Tangerang Selatan",
      "Memiliki pengetahuan dan pemahaman tentang dasar-dasar akuntansi",
      "Memiliki kemampuan manajerial dengan baik",
      "Resilience, data savvy, and solved oriented",
    ],
    description: [
      "Mencatat dan merekonsiliasi transaksi keuangan seperti pemasukan, pengeluaran, utang dan piutang",
      "Menyiapkan laporan keuangan bulanan dan tahunan",
      "Bekerja sama dengan CFO dalam pemberian nasihat keuangan, penyusunan strategi, dan risk management",
    ],
  },
  {
    id: 7,
    url: "project-and-program",
    link: "bit.ly/EnglishSpaceApplicationForm",
    titleJob: "Project and Program",
    department: "Project",
    skills: ["Idea", "Creative", "Inovation"],
    qualifications: [
      "Mahasiswa/i semester 2-4",
      "Memiliki ketertarikan tinggi dalam bidang edukasi bahasa Inggris dan startup",
      "Preferably domisili di sekitar Jakarta dan Tangerang Selatan",
    ],
    description: [
      "Memiliki tanggung jawab untuk membuat konsep detail suatu project baik dari sistem, alur, pengembangan, dan bagaimana mengeksekusinya",
      "Berkomitmen untuk bekerja dan belajar secara konstan",
      "Memiliki kemampuan berpikir kreatif dan inovatif untuk menciptakan ide-ide pengembangan project",
      "Kritis dalam menyikapi suatu permasalahan dan menganalisa cara paling efektif untuk menyelesaikannya",
      "Berpengalaman menjadi panitia pengelola suatu acara",
    ],
  },
  {
    id: 8,
    url: "public-relation",
    link: "bit.ly/EnglishSpaceApplicationForm",
    titleJob: "Public Relation",
    department: "Project",
    skills: ["Developing", "Strategy", "Communication"],
    qualifications: [
      "Mahasiswa/i semester 2-4",
      "Memiliki ketertarikan tinggi dalam bidang edukasi bahasa Inggris dan startup",
      "Preferably domisili di sekitar Jakarta dan Tangerang Selatan",
    ],
    description: [
      "Memiliki tanggung jawab dalam hubungan eksternal project, seperti merancang strategi mempublikasikan suatu project, bagaimana cara mencari partner, customer service, dsb. Divisi ini akan bersinergi langsung dengan department Brand & Marketing",
      "Berkomitmen untuk bekerja dan belajar secara konstan",
      "Memiliki kemampuan berkomunikasi yang baik",
      "Kritis dalam menganalisis target suatu project",
      "Mampu mencari partner yang tepat untuk project",
      "Bisa melayani delegates/customer dengan baik",
      "Memiliki relasi yang luas dan strategi yang efektif untuk mengembangkannya",
    ],
  },
  {
    id: 9,
    url: "administration",
    link: "bit.ly/EnglishSpaceApplicationForm",
    titleJob: "Administration",
    department: "Project",
    skills: ["Tracking", "Pencatatan", "Laporan"],
    qualifications: [
      "Mahasiswa/i semester 2-4",
      "Memiliki ketertarikan tinggi dalam bidang edukasi bahasa Inggris dan startup",
      "Preferably domisili di sekitar Jakarta dan Tangerang Selatan",
    ],
    description: [
      "Memiliki fungsi dan tanggung jawab untuk melakukan pencatatan sementara terkait project yang sedang dikerjakan untuk memudahkan laporan",
      "Berkomitmen untuk bekerja dan belajar secara konstan",
      "Mampu menggunakan tools yang diperlukan untuk tracking dan pencatatan",
      "Mampu membuat laporan suatu project dengan jelas",
    ],
  },
  {
    id: 10,
    url: "social-media",
    link: "bit.ly/EnglishSpaceApplicationForm",
    titleJob: "Social Media",
    department: "Marketing",
    skills: ["Branding", "Content Planning", "Analysis"],
    qualifications: [
      "Mahasiswa/i semester 2-4",
      "Memiliki ketertarikan tinggi dalam bidang edukasi bahasa Inggris dan startup",
      "Preferably domisili di sekitar Jakarta dan Tangerang Selatan",
      "Mampu mengelola media sosial",
      "Mampu berkomunikasi dengan efektif",
      "Mampu menganalisis trend",
      "Mampu mengelola brand image",
      "Kreatif, dan ability to think outside the box",
    ],
    description: [
      "Melakukan image branding untuk platform kita",
      "Membuat content planning (monthly)",
      "Membuat konten digital secara rutin",
      "Melakukan brand research",
      "Membuat digital campaign untuk platform kita",
      "Memantau dan menganalisis media sosial",
      "Melakukan brand ambassador dan influencer research",
      "Menjalankan acara kolaborasi dengan mitra dan universitas (seperti: live instagram, podcast, dll)",
    ],
  },
  {
    id: 11,
    url: "project-marketing",
    link: "bit.ly/EnglishSpaceApplicationForm",
    titleJob: "Project Marketing",
    department: "Marketing",
    skills: ["Research", "Planning", "Communication"],
    qualifications: [
      "Mahasiswa/i semester 2-4",
      "Memiliki ketertarikan tinggi dalam bidang edukasi bahasa Inggris dan startup",
      "Preferably domisili di sekitar Jakarta dan Tangerang Selatan",
      "Mampu berkomunikasi dengan efektif",
      "Mampu berjualan dan bernegosiasi",
      "Memahami konsep dasar strategi pemasaran",
      "Mampu memahami project atau product yang dijual",
      "Mampu mengimplementasikan strategi pemasaran dengan baik",
    ],
    description: [
      "Melakukan market research tentang produk kita",
      "Membuat marketing plan",
      "Menjalankan rencana pemasaran untuk produk kita",
      "Menjual produk kita untuk mendapatkan target pendaftaran",
      "Menjalankan aktivitas pemasaran digital untuk menarik pelanggan",
      "Mengelola dan mengembangkan aktivitas terhadap calon pelanggan",
    ],
  },
  {
    id: 12,
    url: "creative-design",
    link: "bit.ly/EnglishSpaceApplicationForm",
    titleJob: "Creative Design",
    department: "Marketing",
    skills: ["Design", "Adobe", "Creative", "Inovation"],
    qualifications: [
      "Mahasiswa/i semester 2-4",
      "Memiliki ketertarikan tinggi dalam bidang edukasi bahasa Inggris dan startup",
      "Preferably domisili di sekitar Jakarta dan Tangerang Selatan",
      "Memiliki pengalaman dalam bidang desain grafis",
      "Menguasai software desain grafis ex: Adobe Illustrator, Photoshop, CorelDraw, Affinity Designer, dsb",
      "Mampu melakukan tugas dengan cepat atau mendekati deadline",
      "Aktif, kreatif, dan inovatif",
      "Wajib melampirkan portofolio",
      "Dapat membuat aset ilustrasi & content planner menjadi nilai tambah",
    ],
    description: [
      "Melakukan synergy meeting dengan anggota divisi marketing",
      "Membuat final content untuk media sosial kita",
      "Membuat visualisasi untuk desain logo, kemasan produk, atau materi kampanye pemasaran kita",
      "Menerapkan ide atau mencari ide baru berdasarkan permintaan dari Brand Marketing, Product Marketing, dan klien",
      "Melakukan riset tren untuk desain merek kita",
    ],
  },
];
